#!/usr/bin/env python3
"""
Sample Review Generator
Selects 10% random sample from processed skills for verification.
Generates review tasks that can be delegated to subagents.
"""

import json
import random
from pathlib import Path
from datetime import datetime
from typing import List, Dict

# Configuration
REPO_ROOT = Path("/home/sephiroth/Work/overpowers")
PROCESSING_LOG = REPO_ROOT / ".docs" / "batch-processing-log.json"
SAMPLE_REVIEW_FILE = REPO_ROOT / ".docs" / "sample-review-tasks.md"


def load_processing_log() -> Dict:
    """Load the processing log."""
    if not PROCESSING_LOG.exists():
        print(f"❌ Processing log not found: {PROCESSING_LOG}")
        return {}
    
    try:
        with open(PROCESSING_LOG, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"❌ Failed to load processing log: {e}")
        return {}


def select_random_sample(all_results: List[Dict], sample_percent: float = 0.10) -> List[Dict]:
    """Select random sample of processed skills for review."""
    # Filter only successfully processed skills
    processed = [r for r in all_results if r.get('status') == 'processed']
    
    if not processed:
        return []
    
    # Calculate sample size (10%)
    sample_size = max(1, int(len(processed) * sample_percent))
    
    # Select random sample
    sample = random.sample(processed, sample_size)
    
    # Sort by batch for organized review
    sample.sort(key=lambda x: (x.get('batch', ''), x.get('name', '')))
    
    return sample


def generate_review_tasks(sample: List[Dict]) -> str:
    """Generate markdown review tasks for subagents."""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    content = f"""# Sample Review Tasks - Batch Processing Verification

**Generated**: {timestamp}  
**Sample Size**: {len(sample)} skills (10% of processed)  
**Purpose**: Quality verification before staging cleanup

## Review Instructions

For each skill in the sample:

1. **Verify Destination File Exists**
   - Check if `skills/<skill-name>/SKILL.md` exists
   - File should be readable and properly formatted

2. **Verify Frontmatter**
   - `name:` field exists and is in kebab-case
   - `description:` field exists and is NOT empty
   - `metadata:` section exists with category and tags

3. **Verify Content**
   - Content is readable (UTF-8 encoding)
   - No obvious formatting issues
   - No broken links or references

4. **Mark Result**
   - ✅ PASS - Skill is properly formatted and complete
   - ⚠️  WARNING - Minor issues but usable
   - ❌ FAIL - Major issues requiring reprocessing

---

## Review Tasks

"""
    
    # Group by batch for organized review
    batches = {}
    for skill in sample:
        batch_id = skill.get('batch', 'unknown')
        if batch_id not in batches:
            batches[batch_id] = []
        batches[batch_id].append(skill)
    
    for batch_id in sorted(batches.keys()):
        batch_skills = batches[batch_id]
        content += f"\n### Batch {batch_id} ({len(batch_skills)} skills)\n\n"
        
        for i, skill in enumerate(batch_skills, 1):
            skill_name = skill.get('name', 'unknown')
            dest_file = skill.get('destination', 'N/A')
            source_file = skill.get('source', 'N/A')
            
            content += f"""#### Task {i}: Review `{skill_name}`

- [ ] **File Check**: Verify `{dest_file}` exists and is readable
- [ ] **Frontmatter Check**: Verify name, description (non-empty), metadata
- [ ] **Content Check**: Verify UTF-8 encoding, no formatting issues
- [ ] **Result**: [ ] PASS  [ ] WARNING  [ ] FAIL

**Notes**: 
- Source (staging): `{source_file}` (should NOT exist after cleanup)
- Destination: `{dest_file}`

---

"""
    
    content += f"""
## Summary

| Batch | Total Reviewed | PASS | WARNING | FAIL |
|-------|---------------|------|---------|------|
"""
    
    for batch_id in sorted(batches.keys()):
        batch_count = len(batches[batch_id])
        content += f"| {batch_id} | {batch_count} | - | - | - |\n"
    
    content += f"""
**Overall Status**: ⏳ Pending Review

## Next Steps

1. Delegate these review tasks to subagents (divide by batch)
2. Collect review results
3. If all PASS or minor WARNINGs → proceed with cleanup
4. If any FAIL → investigate and fix before cleanup

---

*Generated by sample-review-generator.py*
"""
    
    return content


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate sample review tasks from processed skills')
    parser.add_argument('--sample-percent', type=float, default=0.10,
                       help='Percentage of skills to sample (default: 0.10 = 10%)')
    parser.add_argument('--output', type=str, default=str(SAMPLE_REVIEW_FILE),
                       help=f'Output file for review tasks (default: {SAMPLE_REVIEW_FILE})')
    
    args = parser.parse_args()
    
    # Load processing log
    processing_log = load_processing_log()
    if not processing_log:
        return 1
    
    # Collect all results
    all_results = []
    for batch_id, batch_data in processing_log.get('batches', {}).items():
        all_results.extend(batch_data.get('results', []))
    
    if not all_results:
        print(f"❌ No processing results found")
        return 1
    
    # Count processed skills
    processed_count = sum(1 for r in all_results if r.get('status') == 'processed')
    print(f"\n📊 Processing Statistics:")
    print(f"   Total skills in log: {len(all_results)}")
    print(f"   Successfully processed: {processed_count}")
    
    # Select random sample
    sample = select_random_sample(all_results, args.sample_percent)
    
    if not sample:
        print(f"❌ No processed skills found to sample")
        return 1
    
    sample_size = len(sample)
    sample_percent_display = sample_size / processed_count * 100 if processed_count > 0 else 0
    
    print(f"\n✅ Selected {sample_size} skills for review ({sample_percent_display:.1f}%)")
    
    # Generate review tasks
    review_content = generate_review_tasks(sample)
    
    # Write to file
    output_file = Path(args.output)
    output_file.write_text(review_content, encoding='utf-8')
    
    print(f"\n📝 Review tasks saved to: {output_file}")
    print(f"\n📋 Sample breakdown by batch:")
    
    # Show breakdown
    batches = {}
    for skill in sample:
        batch_id = skill.get('batch', 'unknown')
        if batch_id not in batches:
            batches[batch_id] = 0
        batches[batch_id] += 1
    
    for batch_id in sorted(batches.keys()):
        print(f"   Batch {batch_id}: {batches[batch_id]} skills")
    
    print(f"\n🔄 Next: Delegate review tasks to subagents")
    print(f"   Command: delegate review of batches to subagents")
    
    return 0


if __name__ == '__main__':
    exit(main())
