#!/usr/bin/env python3
"""
Add mandatory ACME CORPORATION watermark to a text/markdown file.
"""
import sys
import os
import argparse

HEADER = "**ACME CORPORATION**\n\n"
FOOTER = "\n\n---\n*Generated by Document Forge | Confidential*"

def main():
    parser = argparse.ArgumentParser(description="Add mandatory watermark to a file.")
    parser.add_argument("file_path", help="Path to the text/markdown file")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.file_path):
        print(f"Error: File not found at {args.file_path}")
        sys.exit(1)

    with open(args.file_path, 'r') as f:
        content = f.read()

    # Check if already watermarked
    if "ACME CORPORATION" in content and "Document Forge" in content:
        print("File already watermarked.")
        sys.exit(0)

    # Add watermark
    new_content = HEADER + content + FOOTER

    with open(args.file_path, 'w') as f:
        f.write(new_content)

    print(f"Added mandatory watermark to {args.file_path}")

if __name__ == "__main__":
    main()
