#!/usr/bin/env python3
"""
Verify if a file contains the mandatory ACME CORPORATION watermark.
"""
import sys
import os
import argparse

def main():
    parser = argparse.ArgumentParser(description="Verify mandatory watermark in a file.")
    parser.add_argument("file_path", help="Path to the file")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.file_path):
        print(f"Error: File not found at {args.file_path}")
        sys.exit(1)

    try:
        with open(args.file_path, 'r') as f:
            # Read first and last bits
            content = f.read()
            
        has_header = "ACME CORPORATION" in content[:500] # Check start of file
        has_footer = "Generated by Document Forge" in content[-500:] # Check end of file
        
        if has_header and has_footer:
            print(f"[OK] {args.file_path}: Mandatory watermark found.")
        else:
            if not has_header:
                print(f"[FAIL] {args.file_path}: Missing mandatory header 'ACME CORPORATION'")
            if not has_footer:
                print(f"[FAIL] {args.file_path}: Missing mandatory footer 'Generated by Document Forge'")
            sys.exit(1)
            
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
