#!/usr/bin/env python3
import os
import sys

def generate_boilerplate(name):
    os.makedirs(name, exist_ok=True)
    
    # main.py
    with open(os.path.join(name, "main.py"), "w") as f:
        f.write(f'''import click

@click.group()
def cli():
    """{name.capitalize()} CLI tool."""
    pass

@cli.command()
@click.option('--name', '-n', default='World')
def hello(name):
    """Greet someone."""
    click.echo(f'Hello {{name}}!')

if __name__ == "__main__":
    cli()
''')

    # requirements.txt
    with open(os.path.join(name, "requirements.txt"), "w") as f:
        f.write("click\n")

    # README.md
    with open(os.path.join(name, "README.md"), "w") as f:
        f.write(f"# {name.capitalize()}\n\nBasic CLI tool generated by personal-tool-builder skill.\n")

    print(f"Boilerplate for {name} generated successfully.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: gen_python_cli.py <project_name>")
        sys.exit(1)
    generate_boilerplate(sys.argv[1])
