#!/bin/bash
# Run python script with AOTI debug flags
SCRIPT_PATH=$1
shift
AOTI_RUNTIME_CHECK_INPUTS=1 \
TORCHINDUCTOR_NAN_ASSERTS=1 \
PYTORCH_NO_CUDA_MEMORY_CACHING=1 \
CUDA_LAUNCH_BLOCKING=1 \
AOT_INDUCTOR_DEBUG_INTERMEDIATE_VALUE_PRINTER=3 \
python "$SCRIPT_PATH" "$@"
