#!/bin/bash
echo "## 🐛 Bug Report"
echo ""
echo "### Problem Description"
echo "[Clear description of the issue]"
echo ""
echo "### Expected Behavior"
echo "[What should happen]"
echo ""
echo "### Actual Behavior"
echo "[What actually happens]"
echo ""
echo "### Reproduction Steps"
echo "1. [Step 1]"
echo "2. [Step 2]"
echo "3. [Step 3]"
echo ""
echo "### Environment"
echo "- Package: [package name and version]"
echo "- Node.js: [version]"
echo "- OS: [operating system]"
echo ""
echo "---"
echo "🤖 Generated with Claude Code"
