import argparse

def export_parser(vendor, output_file):
    print(f"Exporting parser code for vendor: {vendor}")

    template = f"""#!/usr/bin/env python3
\"\"\"
Allotrope ASM Parser for {vendor}
Generated by Claude Code Instrument Data Converter
\"\"\"

import json
import sys
from pathlib import Path

try:
    from allotropy.parser_factory import Vendor
    from allotropy.to_allotrope import allotrope_from_file
except ImportError:
    print("Error: allotropy package is required. Run: pip install allotropy")
    sys.exit(1)

def parse_file(input_path: str, output_path: str = None) -> dict:
    \"\"\"
    Parse {vendor} instrument data to Allotrope Simple Model (ASM).

    Args:
        input_path: Path to the raw instrument output file
        output_path: Optional path to save the ASM JSON

    Returns:
        dict: The parsed ASM data
    \"\"\"
    input_file = Path(input_path)
    if not input_file.exists():
        raise FileNotFoundError(f"Input file not found: {{input_path}}")

    print(f"Parsing {{input_path}} using vendor {{Vendor.{vendor}.name}}...")

    try:
        # Generate ASM dict
        asm_data = allotrope_from_file(str(input_path), Vendor.{vendor})

        # Save to file if requested
        if output_path:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(asm_data, f, indent=2)
            print(f"Saved ASM to {{output_path}}")

        return asm_data

    except Exception as e:
        print(f"Parsing failed: {{e}}")
        raise

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: python {{sys.argv[0]}} <input_file> [output_json]")
        sys.exit(1)

    input_f = sys.argv[1]
    output_f = sys.argv[2] if len(sys.argv) > 2 else f"{{Path(input_f).stem}}_asm.json"

    parse_file(input_f, output_f)
"""

    with open(output_file, 'w') as f:
        f.write(template)

    print(f"Exported parser to {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export standalone Python parser script")
    parser.add_argument("--vendor", required=True, help="Allotropy Vendor enum name")
    parser.add_argument("--output", default="parser_script.py", help="Output python file path")
    args = parser.parse_args()

    export_parser(args.vendor, args.output)
