#!/usr/bin/env python3
import argparse
import sys
import os

def create_hook(hook_type, hook_name):
    # Determine the directory
    if not os.path.exists('.githooks'):
        os.makedirs('.githooks')

    hook_path = os.path.join('.githooks', hook_type)

    # Template logic
    if hook_type == 'pre-commit':
        content = """#!/bin/bash
# Pre-commit hook generated by Hook Factory
set -e

echo "Running pre-commit checks..."
# Add your linting or checking commands here
# e.g., npm run lint, pytest, etc.

echo "Pre-commit checks passed."
"""
    elif hook_type == 'pre-push':
        content = """#!/bin/bash
# Pre-push hook generated by Hook Factory
set -e

echo "Running pre-push checks..."
# Add your testing or checking commands here
# e.g., npm test, pytest, etc.

echo "Pre-push checks passed."
"""
    else:
        content = f"""#!/bin/bash
# {hook_type} hook generated by Hook Factory
set -e

echo "Running {hook_type} checks..."
"""

    with open(hook_path, 'w') as f:
        f.write(content)

    os.chmod(hook_path, 0o755)
    print(f"[*] Hook '{hook_type}' created at {hook_path}")
    print("[*] Don't forget to run 'git config core.hooksPath .githooks' if this is your first hook.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Hook Factory - Git Hook Generator")
    parser.add_argument("-t", "--type", required=True, choices=["pre-commit", "pre-push", "post-checkout", "post-merge", "pre-rebase"], help="Type of Git hook to generate")
    parser.add_argument("-n", "--name", help="Optional name/description for the hook")

    args = parser.parse_args()
    create_hook(args.type, args.name)
