#!/usr/bin/env python3
"""
Convert raw PCM audio generated by Azure OpenAI Realtime API to standard WAV format.
"""
import sys
import wave

def pcm_to_wav(pcm_data: bytes, output_path: str, sample_rate: int = 24000):
    """
    Convert PCM to WAV.
    Assuming 16-bit PCM, mono channel from GPT Realtime API.
    """
    try:
        with wave.open(output_path, 'wb') as wav_file:
            wav_file.setnchannels(1)  # Mono
            wav_file.setsampwidth(2)  # 16-bit
            wav_file.setframerate(sample_rate)
            wav_file.writeframes(pcm_data)
        print(f"Successfully converted to {output_path}")
    except Exception as e:
        print(f"Failed to convert PCM to WAV: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input_pcm> <output_wav> [sample_rate]")
        sys.exit(1)

    input_pcm = sys.argv[1]
    output_wav = sys.argv[2]
    sample_rate = int(sys.argv[3]) if len(sys.argv) > 3 else 24000

    with open(input_pcm, 'rb') as f:
        pcm_data = f.read()

    pcm_to_wav(pcm_data, output_wav, sample_rate)
