#!/usr/bin/env python3
"""
Organize non-English files into translation batches of 30.
Creates task files for batch processing.
"""

import json
from pathlib import Path
from collections import defaultdict

# Base directory
BASE_DIR = Path("/home/sephiroth/Work/overpowers")
OUTPUT_DIR = BASE_DIR / ".docs" / "tasks"
PLANNING_DIR = OUTPUT_DIR / "planning"
NON_ENGLISH_DATA = PLANNING_DIR / "non-english-data.json"

BATCH_SIZE = 30


def load_non_english_data():
    """Load the non-English detection data"""
    if not NON_ENGLISH_DATA.exists():
        print(f"❌ Data file not found: {NON_ENGLISH_DATA}")
        print("Run detect-non-english.py first!")
        return None
    
    with open(NON_ENGLISH_DATA, 'r', encoding='utf-8') as f:
        return json.load(f)


def organize_batches(non_english_files, category, start_batch=1):
    """Organize files into batches of 30"""
    batches = []
    current_batch = []
    
    for file_info in non_english_files:
        current_batch.append(file_info)
        
        if len(current_batch) >= BATCH_SIZE:
            batches.append(current_batch)
            current_batch = []
    
    # Add remaining files
    if current_batch:
        batches.append(current_batch)
    
    return batches


def create_task_file(batch_num, batch_files, category):
    """Create a task markdown file for a batch"""
    task_num = f"0510-{category}-batch-{batch_num:03d}"
    task_file = OUTPUT_DIR / f"{task_num}.md"
    
    content = []
    content.append(f"# Translation Task: {task_num}\n")
    content.append(f"**Category**: {category}\n")
    content.append(f"**Batch Size**: {len(batch_files)} files\n")
    content.append(f"**Priority**: High (non-English content)\n\n")
    
    content.append("## Objective\n")
    content.append("Translate all files in this batch to English. Ensure:\n")
    content.append("1. Frontmatter metadata (name, description) is in English\n")
    content.append("2. Content is translated accurately\n")
    content.append("3. Technical terms remain unchanged\n")
    content.append("4. Code blocks and examples are preserved\n")
    content.append("5. Links and references are updated if needed\n\n")
    
    content.append("## Instructions\n")
    content.append("For each file:\n")
    content.append("1. Read the original content\n")
    content.append("2. Translate to English (use AI assistance if needed)\n")
    content.append("3. Update frontmatter with English name/description\n")
    content.append("4. Review for accuracy and completeness\n")
    content.append("5. Check off the item when done\n\n")
    
    content.append("## Files to Translate\n\n")
    
    for i, file_info in enumerate(batch_files, 1):
        file_path = file_info['path']
        detected_langs = ", ".join(f"{k} ({v['percentage']}%)" for k, v in file_info.get('detected_languages', {}).items())
        confidence = file_info.get('confidence', 0)
        size = file_info.get('size_kb', 0)
        
        content.append(f"### {i}. `{file_path}`\n")
        content.append(f"- **Languages Detected**: {detected_langs}\n")
        content.append(f"- **Confidence**: {confidence:.1%}\n")
        content.append(f"- **Size**: {size} KB\n")
        
        if file_info.get('metadata', {}).get('name'):
            content.append(f"- **Current Name**: {file_info['metadata']['name']}\n")
        if file_info.get('metadata', {}).get('description'):
            content.append(f"- **Current Description**: {file_info['metadata']['description']}\n")
        
        content.append(f"- [ ] Translate to English\n\n")
    
    content.append("---\n")
    content.append("*Generated by organize-translation-batches.py*\n")
    
    return task_file, "\n".join(content)


def create_summary_report(all_batches):
    """Create a summary report of all batches"""
    report = []
    report.append("# Translation Batches Summary\n")
    report.append(f"**Batch Size**: {BATCH_SIZE} files per batch\n")
    report.append(f"**Total Batches**: {sum(len(b) for b in all_batches.values())}\n\n")
    
    report.append("## Batches by Category\n\n")
    
    for category, batches in all_batches.items():
        report.append(f"### {category.title()}\n")
        report.append(f"**Total Batches**: {len(batches)}\n")
        report.append(f"**Total Files**: {sum(len(b) for b in batches)}\n\n")
        
        report.append("| Batch # | Files | Task File |\n")
        report.append("|---------|-------|-----------|\n")
        
        for i, batch in enumerate(batches, 1):
            task_num = f"0510-{category}-batch-{i:03d}"
            report.append(f"| {i} | {len(batch)} | `{task_num}.md` |\n")
        
        report.append("\n")
    
    report.append("## Priority Order\n")
    report.append("1. **Skills** - Largest category, most impact\n")
    report.append("2. **Agents** - Core functionality\n")
    report.append("3. **Workflows** - Process documentation\n")
    report.append("4. **Hooks** - Configuration files\n\n")
    
    report.append("## Estimated Effort\n")
    total_files = sum(len(b) for batches in all_batches.values() for b in batches)
    report.append(f"- Total files to translate: {total_files}\n")
    report.append(f"- Estimated time per file: 10-30 minutes\n")
    report.append(f"- Total estimated time: {total_files * 20 / 60:.0f}-{total_files * 30 / 60:.0f} hours\n\n")
    
    return "\n".join(report)


def main():
    print("📦 Organizing Translation Batches\n")
    print("=" * 60)
    
    # Load data
    data = load_non_english_data()
    if not data:
        return
    
    # Organize by category
    all_batches = {}
    
    for category in ['skills', 'agents', 'workflows', 'hooks']:
        non_english = data.get('non_english', {}).get(category, [])
        mixed = data.get('mixed', {}).get(category, [])
        
        # Combine non-English and mixed
        all_non_english = non_english + mixed
        
        if all_non_english:
            batches = organize_batches(all_non_english, category)
            all_batches[category] = batches
            
            print(f"\n{category.upper()}:")
            print(f"  Total files: {len(all_non_english)}")
            print(f"  Batches created: {len(batches)}")
            
            # Create task files
            for i, batch in enumerate(batches, 1):
                task_file, content = create_task_file(i, batch, category)
                with open(task_file, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                if i <= 3 or i == len(batches):  # Print first 3 and last
                    print(f"    ✓ Created {task_file.name}")
            
            if len(batches) > 3:
                print(f"    ... and {len(batches) - 3} more batches")
    
    # Create summary report
    summary = create_summary_report(all_batches)
    summary_file = PLANNING_DIR / "translation-batches-summary.md"
    with open(summary_file, 'w', encoding='utf-8') as f:
        f.write(summary)
    
    print(f"\n✅ Summary saved to: {summary_file}")
    
    # Print final summary
    print("\n" + "=" * 60)
    print("📊 FINAL SUMMARY:")
    total_batches = sum(len(b) for b in all_batches.values())
    total_files = sum(
        len(batch) 
        for batches in all_batches.values() 
        for batch in batches
    )
    print(f"  Total batches created: {total_batches}")
    print(f"  Total files to translate: {total_files}")
    print(f"  Task files created: {total_batches}")
    print(f"  Location: .docs/tasks/0510-*-batch-*.md")
    print("=" * 60)


if __name__ == "__main__":
    main()
