#!/bin/bash
# Generate a skeleton HTML for a sales asset

PROSPECT_NAME=${1:-"Prospect"}
ASSET_TYPE=${2:-"landing-page"}
DATE=$(date +%Y-%m-%d)
FILENAME="${PROSPECT_NAME}-${ASSET_TYPE}-${DATE}.html"

cat > "$FILENAME" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$PROSPECT_NAME - Sales Asset</title>
    <style>
        :root {
            --primary: #3b82f6;
            --bg: #0a0d14;
            --text: #ffffff;
        }
        body { font-family: sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }
        .container { max-width: 800px; margin: 0 auto; }
        h1 { color: var(--primary); }
    </style>
</head>
<body>
    <div class="container">
        <h1>$PROSPECT_NAME - Strategic Partnership</h1>
        <p>Type: $ASSET_TYPE</p>
        <!-- Content will be generated by AI -->
    </div>
</body>
</html>
EOF

echo "Asset skeleton generated: $FILENAME"
