git clone https://github.com/0xfurai/claude-code-subagents 0xfurai-claude-code-subagents
git clone https://github.com/AIPexStudio/AIPex AIPexStudio-AIPex
git clone https://github.com/BreezeAllen/aidevops BreezeAllen-aidevops
git clone https://github.com/ChihiroNishioka/AntigravitySkills ChihiroNishioka-AntigravitySkills
git clone https://github.com/ComposioHQ/awesome-claude-skills ComposioHQ-awesome-claude-skills
git clone https://github.com/Dicklesworthstone/claude_code_agent_farm Dicklesworthstone-claude_code_agent_farm
git clone https://github.com/DiscreteTom/agent-skills-mcp DiscreteTom-agent-skills-mcp
git clone https://github.com/DonggangChen/antigravity-agentic-skills DonggangChen-antigravity-agentic-skills
git clone https://github.com/DougTrajano/pydantic-ai-skills DougTrajano-pydantic-ai-skills
git clone https://github.com/Equilateral-AI/equilateral-agents-open-core Equilateral-AI-equilateral-agents-open-core
git clone https://github.com/Gnonymous/Skill-Transfer Gnonymous-Skill-Transfer
git clone https://github.com/HeshamFS/materials-simulation-skills HeshamFS-materials-simulation-skills
git clone https://github.com/IncomeStreamSurfer/antigravity-skills IncomeStreamSurfer-antigravity-skills
git clone https://github.com/K-Dense-AI/claude-scientific-skills K-Dense-AI-claude-scientific-skills
git clone https://github.com/Karanjot786/agent-skills-cli Karanjot786-agent-skills-cli
git clone https://github.com/Kyure-A/agent-skills-nix Kyure-A-agent-skills-nix
git clone https://github.com/Larry-kang/antigravity-agent-config Larry-kang-antigravity-agent-config
git clone https://github.com/LunarTechAI/superpowers LunarTechAI-superpowers
git clone https://github.com/NotMyself/claude-win11-speckit-update-skill NotMyself-claude-win11-speckit-update-skill
git clone https://github.com/QuinnRuth/antigravity-skills QuinnRuth-antigravity-skills
git clone https://github.com/SHADOWPR0/beautiful_prose SHADOWPR0-beautiful_prose
git clone https://github.com/SHADOWPR0/security-bluebook-builder SHADOWPR0-security-bluebook-builder
git clone https://github.com/Sounder25/Google-Antigravity-Skills-Library Sounder25-Google-Antigravity-Skills-Library
git clone https://github.com/Therayz1/antigravity-skills-rules-workflows Therayz1-antigravity-skills-rules-workflows
git clone https://github.com/UfoMiao/zcf UfoMiao-zcf
git clone https://github.com/VidyFoo/antigravity-skill-engine VidyFoo-antigravity-skill-engine
git clone https://github.com/VoltAgent/awesome-claude-skills VoltAgent-awesome-claude-skills
git clone https://github.com/WilkoMarketing/antigravity-n8n-skills WilkoMarketing-antigravity-n8n-skills
git clone https://github.com/ZhangHanDong/makepad-skills ZhangHanDong-makepad-skills
git clone https://github.com/alexjiaguo/AntigravitySkills alexjiaguo-AntigravitySkills
git clone https://github.com/alinaqi/claude-bootstrap alinaqi-claude-bootstrap
git clone https://github.com/alirezarezvani/claude-code-skill-factory alirezarezvani-claude-code-skill-factory
git clone https://github.com/anthropics/skills anthropics-skills
git clone https://github.com/as4584/antigravity-skills as4584-antigravity-skills
git clone https://github.com/bmasterson1/.agentskills bmasterson1-.agentskills
git clone https://github.com/charles-adedotun/claude-code-sub-agents charles-adedotun-claude-code-sub-agents
git clone https://github.com/codeF1x/antigravity-skills codeF1x-antigravity-skills
git clone https://github.com/conorluddy/ios_simulator_skill conorluddy-ios-simulator-skill
git clone https://github.com/contains-studio/agents contains-studio-agents
git clone https://github.com/cp09x/antigravity-skills cp09x-antigravity-skills
git clone https://github.com/czlonkowski/n8n-skills czlonkowski-n8n-skills
git clone https://github.com/davepoon/buildwithclaude davepoon-buildwithclaude
git clone https://github.com/dmmulroy/cloudflare-skill dmmulroy-cloudflare-skill
git clone https://github.com/dudqks0319-cpu/antigravity-skills dudqks0319-cpu-antigravity-skills
git clone https://github.com/ethanolivertroy/antigravity-skills ethanolivertroy-antigravity-skills
git clone https://github.com/expo/skills expo-skills
git clone https://github.com/feiskyer/claude-code-settings feiskyer-claude-code-settings
git clone https://github.com/frmoretto/clarity-gate frmoretto-clarity-gate
git clone https://github.com/fvadicamo/dev-agent-skills fvadicamo-dev-agent-skills
git clone https://github.com/gamestap99/ai-antigravity-skill-creator gamestap99-ai-antigravity-skill-creator
git clone https://github.com/getsentry/skills getsentry-skills
git clone https://github.com/gmickel/sheets_cli gmickel-sheets-cli
git clone https://github.com/gotalab/skillport gotalab-skillport
git clone https://github.com/guanyang/antigravity-skills guanyang-antigravity-skills
git clone https://github.com/harikrishna8121999/antigravity-workflows harikrishna8121999-antigravity-workflows
git clone https://github.com/hesreallyhim/a-list-of-claude-code-agents hesreallyhim-a-list-of-claude-code-agents
git clone https://github.com/hesreallyhim/awesome-claude-code hesreallyhim-awesome-claude-code
git clone https://github.com/huifer/Claude-Ally-Health huifer-Claude-Ally-Health
git clone https://github.com/hunter3316/Antigravity_skills hunter3316-Antigravity_skills
git clone https://github.com/huyhoangnhh98/cc2ag huyhoangnhh98-cc2ag
git clone https://github.com/hz1957/rocket-launcher-platform hz1957-rocket-launcher-platform
git clone https://github.com/iamneongo/antigravity-cooking iamneongo-antigravity-cooking
git clone https://github.com/iannuttall/claude-agents iannuttall-claude-agents
git clone https://github.com/ibelick/ui-skills ibelick-ui-skills
git clone https://github.com/its-meseba/antigravity-configuration-and-claude-skills-integration its-meseba-antigravity-configuration-and-claude-skills-integration
git clone https://github.com/jakreymyers/context-engine jakreymyers-context-engine
git clone https://github.com/jakreymyers/myrs-core jakreymyers-myrs-core
git clone https://github.com/jakreymyers/myrs-git-flow jakreymyers-myrs-git-flow
git clone https://github.com/jakreymyers/outreach-engine jakreymyers-outreach-engine
git clone https://github.com/jeffersonwarrior/claudisms jeffersonwarrior-claudisms
git clone https://github.com/joshkellett87/useful-skills joshkellett87-useful-skills
git clone https://github.com/jswortz/antigravity-claude-skills jswortz-antigravity-claude-skills
git clone https://github.com/jthack/ffuf_claude_skill jthack-ffuf_claude_skill
git clone https://github.com/lackeyjb/playwright_skill lackeyjb-playwright-skill
git clone https://github.com/lasoons/AgentSkillsManager lasoons-AgentSkillsManager
git clone https://github.com/lawvable/awesome-legal-skills lawvable-awesome-legal-skills
git clone https://github.com/lips85/antigravity-skills-bootstrap lips85-antigravity-skills-bootstrap
git clone https://github.com/lst97/claude-code-sub-agents lst97-claude-code-sub-agents
git clone https://github.com/marcusquinn/aidevops marcusquinn-aidevops
git clone https://github.com/masch/antigravity-skills masch-antigravity-skills
git clone https://github.com/mehdiozdemir/awesome-agent-skills mehdiozdemir-awesome-agent-skills
git clone https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering muratcankoylan-Agent-Skills-for-Context-Engineering
git clone https://github.com/netresearch/claude-code-marketplace netresearch-claude-code-marketplace
git clone https://github.com/nextlevelbuilder/ui_ux_pro_max-skill nextlevelbuilder-ui-ux-pro-max-skill
git clone https://github.com/nguyenphp/antigravity-marketing nguyenphp-antigravity-marketing
git clone https://github.com/nickdesi/skills4Antigravity nickdesi-skills4Antigravity
git clone https://github.com/nicolasestrem/antigravity-gemini-skills nicolasestrem-antigravity-gemini-skills
git clone https://github.com/omkamal/pypict-claude-skill omkamal-pypict-claude-skill
git clone https://github.com/paleo/alignfirst paleo-alignfirst
git clone https://github.com/patchy631/ai_engineering-hub patchy631-ai-engineering-hub
git clone https://github.com/phuthuycoding/moicle phuthuycoding-moicle
git clone https://github.com/pnocera/skilld pnocera-skilld
git clone https://github.com/ppai-id/Antigravity-skills ppai-id-Antigravity-skills
git clone https://github.com/rahulvrane/awesome-claude-agents rahulvrane-awesome-claude-agents
git clone https://github.com/rmyndharis/antigravity-skills rmyndharis-antigravity-skills
git clone https://github.com/rominirani/antigravity-skills rominirani-antigravity-skills
git clone https://github.com/runkids/skillshare runkids-skillshare
git clone https://github.com/ruvnet/claude-flow ruvnet-claude-flow
git clone https://github.com/sanjay3290/ai-skills sanjay3290-ai-skills
git clone https://github.com/sazerfenor/antigravityskills-com sazerfenor-antigravityskills-com
git clone https://github.com/scarletkc/vexor scarletkc-vexor
git clone https://github.com/sdaulibin/antigravity-skills sdaulibin-antigravity-skills
git clone https://github.com/sickn33/antigravity-awesome-skills sickn33-antigravity-awesome-skills
git clone https://github.com/skillmatic-ai/awesome-agent-skills skillmatic-ai-awesome-agent-skills
git clone https://github.com/supatest-ai/awesome-claude-code-sub-agents supatest-ai-awesome-claude-code-sub-agents
git clone https://github.com/tknvstp/antigravity-skills tknvstp-antigravity-skills
git clone https://github.com/tomokazutateishi/antigravity-skills tomokazutateishi-antigravity-skills
git clone https://github.com/trailofbits/skills trailofbits-skills
git clone https://github.com/vercel-labs/agent-skills vercel-labs-agent-skills
git clone https://github.com/vijaythecoder/awesome-claude-agents vijaythecoder-awesome-claude-agents
git clone https://github.com/vuralserhat86/antigravity-agentic-skills vuralserhat86-antigravity-agentic-skills
git clone https://github.com/webdevtodayjason/sub-agents webdevtodayjason-sub-agents
git clone https://github.com/wrsmith108/linear-claude-skill wrsmith108-linear-claude-skill
git clone https://github.com/wrsmith108/varlock-claude-skill wrsmith108-varlock-claude-skill
git clone https://github.com/wshobson/agents wshobson-agents
git clone https://github.com/wshobson/commands wshobson-commands
git clone https://github.com/wshuyi/x-article-publisher-skill wshuyi-x-article-publisher-skill
git clone https://github.com/zhsama/claude-sub-agent zhsama-claude-sub-agent
git clone https://github.com/zxkane/aws-skills zxkane-aws-skills
